language: node_js
node_js:
  - "11.10.1"
env:
  global:
    - CC_TEST_REPORTER_ID=0b88681771ae84256e88bf6320b5262a2cec5ec5a40dc79780535f9245ee71fd
  matrix:
    - REACT=16.7

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: npm test -- -u

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
