pipeline {
  agent {
    kubernetes {
      label 'sendit'
      defaultContainer 'jnlp'
      yamlFile 'jenkins/agent.yaml'
    }
  }

  stages {
    stage('Build') {
        steps {
            container('sendit') {
              sh "npm install"
            }
        }
      }

    stage('Test'){
      steps {
        container('sendit') {
          // sh "npm test -- -u"
        }
      }
    }
    stage('Bake'){
      steps {
        container('sendit') {
          sh "docker ps"
          // sh "chmod +x scripts/ && ./scripts/bake.sh"
        }
      }
    }
  }
}
            