pipeline {
  agent {
    kubernetes {
      label 'sendit'
      defaultContainer 'jnlp'
      yamlFile 'jenkins/agent.yaml'
    }
  }
  environment {
    GCLOUD_SERVICE_KEY  = credentials('GCLOUD_SERVICE_KEY')
  }

  stages {
    stage('Build') {
        steps {
            container('sendit') {
              sh "npm install"
            }
        }
      }

    stage('Test'){
      steps {
        container('sendit') {
          sh "npm test -- -u"
        }
      }
    }
    stage('Bake'){
      steps {
        container('sendit') {
          withCredentials([
            file(credentialsId: 'SENDIT_ENV', variable: 'ENV_FILE')
          ]) {
            load "$ENV_FILE"
          }
          sh "chmod +x jenkins/scripts/* && ./jenkins/scripts/bake.sh"
        }
      }
    }
  }
}
